language: python
python:
- '3.6'
install:
- pip install -r test_requirements.txt
script: pytest
env:
  global:
  - FLASK_CONFIG=config.TestConfig
  - CF_API=https://api.cloud.service.gov.uk
  - CF_ORGANIZATION=mhclg-digital-land
  - CF_USERNAME=adam.shimali@gmail.com
  - CF_SPACE=digital-land
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    repo: communitiesuk/brownfield-sites-validator
  password:
    secure: GycjQvxIscAB5oKoR8UCixpR/lLgQ397Vn0qCY2mB471qqCOPN9OrIzChyCdr9X85OGtZdwmCLWiU9LKm2JrhlXF+R/jw9KQQ6OJEcnCd7jm1XyMq83n4lgw3IpKZkp9rlNTJljDqNIsYaR4v0qzihVnckdsCJ7IVo2ik/UlmhCaXTLGigjiXNCBwkYDVl1CKhcp3t6V3HCaKTOlCKVkzMIHt6mQKYlwO/IhZ+waTDDcSAvUtat2lwEk3RbRWxHfrnS5TqYrngcdP+DZbGfcHTvJAPWoKZ6q1S4c8se+dgKjtApzN7U0d1UW6cYC2Iw7uMFOVt3WSMn4jE6Ewunx1yXo8poKwBhrGnBs98QMJtaLV42obBwQyJWPk0xqeTVj7Vbp8GK7VoY8KEPUMIOTm1c0pfMlZObjcnf2rRmHovoSZggqAhK9NQdz6D2SB7uGk8GMiTGVXpgufzfJEfwcdtoVkqhAi96xOJUqom7Tlqsmwq7xjFp+MEN2l1eVRi6fsdLhAl3l/dyfF3rO4H/U3F3NBWrbHrxJ9/oAKv5B4SW7R0NcGcGYDg8vfLsjb19KYaQDPV76uQ0PhDM7b5ZVhAdv+HXdFsC6KIxvCS9yIsV6BrTLAqUAKNgXTdhaWQcTnIMZ0MWBXFCZwhJYZQd+FB6PvKjxe8aTsO9Or+FcsFo=
