language: python
python:
- '3.7.4'
install:
- pip install -r requirements.txt
script: pytest -Wignore

before_script:
 - psql -c 'create database brownfield_test;' -U postgres

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
