language: python
python:
- '3.6'
install:
- pip install -r test_requirements.txt
script: pytest
env:
  global:
  - FLASK_CONFIG=config.TestConfig
  - CF_API=https://api.cloud.service.gov.uk
  - CF_ORGANIZATION=mhclg-digital-land
  - CF_USERNAME=adam.shimali@gmail.com
  - CF_SPACE=digital-land
  - secure: qdNtJ4EGYnaSXkxLNT5xwR4rF4eEf34qoRJzrp7L+Iqhf2Ag320HGSJ1anOQDESvtzmQAG11b+TUzZHMzbuKCFeCPlinABruUoMTeJfOg9V/GwsgCBXCr4k0K10xmq+KwZgYBnVOkEqdhyDhhNP0bS/1JLMlgdcDR0HCol/8+d6WKsYZBSfwjG8JpcJ6ZMnlqUkuQfZ3Vn5PcoVjyAKobL++DN0X6BC6mwOeNZVxX29mr6o/TaDJCAUfAv48eW9ytWNicTBTjfMG/Hqqe7E2sF7nCsRMKRWlhTqDyqOXdwiHUDCRGC5s55s6pdAunhDrPWP5OPPGocc5f0e1WBvBdR4JuaoqKq1wDaiEDD7r1BdGSxo5t+Kt1RvPSkMml9e5M5HkV8abMfQZkQn7Dh/tcOEnXMP7YfB0dG2sMh+tw14cAIc/1MduZxdvJ2sOipD37wRnMtwXO7XpY3Hj4EUMalVyjXWLxZqg/w9UtDeKnC4OzO+9OZRiDvSAlFlvCT+G2DDoESshQ+48MbX/lAkiABm0Lt8ZI0h7ftWcdJnCTxVR0DJfT6OMXduLyH2ehiVx8i5JqcUBcoSMrdq32ln6MhfqRJjSAB9nez9/ens42KVIwjz7s1aEXdxtPEvoq1ks1PjsXR8dnjExBlFBh5IIKsKVER4uUBgWDrA+8EzSipM=
  - secure: nHAlhvF1XvsrbS2Z26e8v2E0JoWzjKbdmG/DdDNExkgnDYx6W78mECbHcLivPLIzUuZRBRBnhWu3c3JNgq9Xl0tRuTvztSOgwPw4JA55ROT9ELRFgskbSilbKBP/mFHRpeyE/Y2XyUsLJEojSjL23BWwPc3zxi9QghLjpCgoCTSHpPfSRUkKCXNPaq3QJOtvyCTaEq28RGNpl8QmBwuS5YltOkZ9YkPOvI8VsCnmz8bOSKXdVai0kHqaCMgwN3eybcbq1MZMJvQ/SGK18zmIRQJX2Yx5NZ3g4jpC7e/0AkYjg55NY+29ZGl2jonSqDB+GKBPg9Rs2sg0mI58ASma0Fs7H+Cx0wgUMQO7Iv6QydUpx0J/OvDnvDB935WD17/1rdIekGWou/U3ls2m7mAH29rpveiWdkN7nS8qXlLRmu5nWrDQVMfcz9+5IznRILB+2k5bGo8Aqh0Ij5kE17K0LVAXDStrdXaHeSuaWq/3nqvF4VlsWZWOxjSt1EaboqPJppY2v72zwHAXL1n9NvGZuwSJrhcrwtfnWMQikmGQsmRW9CtdB1Glx9+osFfwM2CoucNjX1yGe2mc/087gLSSUo16KnST+VVPV/xuG6fnolYAPGvHF6te+0HWAlmBHDmIgfQzCEs4jHDPB/2bwuOrgA3oBMqC8rpKZCSfr6Rnxb4=
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    repo: communitiesuk/brownfield-sites-validator
